import type { NetworkInfo } from "./types";

export const DEFAULT_CHAIN_ID = 11155420;

export const SUPPORTED_NETWORKS: Record<number, NetworkInfo> = {
  1: {
    name: "Ethereum Mainnet",
    rpcUrl: "https://ethereum-rpc.publicnode.com",
    explorer: "https://etherscan.io",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  10: {
    name: "OP Mainnet",
    rpcUrl: "https://mainnet.optimism.io",
    explorer: "https://optimistic.etherscan.io",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  56: {
    name: "BNB Smart Chain",
    rpcUrl: "https://bsc.blockrazor.xyz",
    explorer: "https://bscscan.com",
    nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  97: {
    name: "BNB Smart Chain Testnet",
    rpcUrl: "https://bsc-testnet-rpc.publicnode.com",
    explorer: "https://testnet.bscscan.com",
    nativeCurrency: { name: "Test BNB", symbol: "tBNB", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  8453: {
    name: "Base Mainnet",
    rpcUrl: "https://base.drpc.org",
    explorer: "https://basescan.org",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  84532: {
    name: "Base Sepolia",
    rpcUrl: "https://base-sepolia-rpc.publicnode.com",
    explorer: "https://sepolia.basescan.org",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    contractAddresses: {
      protocolManager: '0x03d10c62c758403758C51BA602b79407CC81F5A4',
      poolDeployer: '0x30164221adACBE21C6147915788B8e367D80bAc5',
      revenueManager: '0x375E45CcFc64349444810Cc3152238429aa98961',
      nftFactory: '0xf74041656A120d41D3eC7265c1301bAAd216013f',
      rewardsFlywheel: '0xEC9aE50558d7dEE8211C3faF2e3ce1cDDa2db8Ec',
      poolRouter: '0x1291657b949c1f3070eC2f236a66299A5FD5f1b1',
      socialEngagementManager: '0x7d371eef83e84702624CeC09e392dBD88A97B330',
      purchaseAuthorizer: '0x7BCCAA360fE0688DcB34Edba87EfEB1C376Abedc'
    },
  },
  11155111: {
    name: "Ethereum Sepolia",
    rpcUrl: "https://sepolia.infura.io",
    explorer: "https://sepolia.etherscan.io",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  11155420: {
    name: "OP Sepolia Testnet",
    rpcUrl: "https://sepolia.optimism.io",
    explorer: "https://sepolia-optimism.etherscan.io",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    contractAddresses: {
      protocolManager: '0xD0aA2A1076c7EFfE6f6DAE959B7e512Ad557F3D9',
      poolDeployer: '0x340d3c4f461A27Ca87BDDBf071eDEF42f605503E',
      revenueManager: '0x3ee6B06e1F1DA1dD8a8809eE19AFe98DA6C5EC4C',
      nftFactory: '0xDCa93973C41915F544f14Ca44de2697028888B1C',
      rewardsFlywheel: '0x7d21c990bf7D2E1d691Cc082F7ba121D3A7d868B',
      socialEngagementManager: '0x4308Fb2CCe656D99D791b48eeACbf0E077D7928C',
      purchaseAuthorizer: '0x7fB0Bb9Ee9a1b20248Ed3E7201fFCd0e8C2E45Db',
      poolRouter: '0x...',
    },
  },
  43113: {
    name: "Avalanche Fuji Testnet",
    rpcUrl: "https://avalanche-fuji.drpc.org",
    explorer: "https://testnet.snowscan.xyz",
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  43114: {
    name: "Avalanche C-Chain",
    rpcUrl: "https://avalanche.drpc.org",
    explorer: "https://snowscan.xyz",
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  2020: {
    name: "Ronin Mainnet",
    rpcUrl: "https://ronin.drpc.org",
    explorer: "https://app.roninchain.com/",
    nativeCurrency: { name: "Ronin", symbol: "RON", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  2021: {
    name: "Ronin Saigon Testnet",
    rpcUrl: "https://saigon-testnet.roninchain.com/rpc",
    explorer: "https://saigon-app.roninchain.com/explorer",
    nativeCurrency: { name: "Ronin", symbol: "RON", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  42161: {
    name: "Arbitrum One",
    rpcUrl: "https://arbitrum.drpc.org",
    explorer: "https://arbiscan.io",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
  421614: {
    name: "Arbitrum Sepolia",
    rpcUrl: "https://endpoints.omniatech.io/v1/arbitrum/sepolia/public",
    explorer: "https://sepolia.arbiscan.io",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    contractAddresses: {
      protocolManager: "0x...",
      poolDeployer: "0x...",
      revenueManager: "0x...",
      nftFactory: "0x...",
      socialEngagementManager: "0x...",
      rewardsFlywheel: "0x...",
      purchaseAuthorizer: "0x...",
      poolRouter: "0x...",
    },
  },
};
